apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muscat-staging-components
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:gudiaolabs/argocd-apps
    path: apps/staging/muscat
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true